version: '3.1'
services:
  mongo:
    image: mongo:3.4.6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
      - ./data:/home/external
  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: taskTrackerApi
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV
    volumes:
      - ./server:/myapp/server
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: taskTrackerClient
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV
    volumes:
      - ./client:/myapp/client